name: ci
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    uses: urianbamboo/.github/.github/workflows/ci-node.yml@v1
    with:
      gate: "make check-ci"
